### ISSUE TITLE
metacat update parents call doesn't always take on first try

### ISSUE THREAD

**Issue by StevenCTimm** [fermitools/metacat#32]
about 10% of the time when we try to do a metacat file update --parents we see an exception and the update does not go through.
This occurs both on CLI and python API

Usually after 2 or 3 retries it does eventually go through
the commands being executed here were

metacat file show fardet-vd:nu_numu2nutau_nue2numu_dunevd10kt_1x8x6_3view_30deg_946_153_20230802T232007Z_gen_g4_detsim_hitreco__20240224T091815Z_reco2_Pandora_Events.pndr -l 

metacat file update fardet-vd:nu_numu2nutau_nue2numu_dunevd10kt_1x8x6_3view_30deg_946_153_20230802T232007Z_gen_g4_detsim_hitreco__20240224T091815Z_reco2_Pandora_Events.pndr --parents '-' --replace

metacat file show fardet-vd:nu_numu2nutau_nue2numu_dunevd10kt_1x8x6_3view_30deg_946_153_20230802T232007Z_gen_g4_detsim_hitreco__20240224T091815Z_reco2_Pandora_Events.pndr -l 

This will presumably become less important with the advent of metacat 4.0 which will not show retired files as parents or children.

checksums:
    adler32   : 648e7fbd
created_timestamp   :	2024-02-24 10:07:36.816310+00:00
creator             :	dunepro
fid                 :	UHIgc9HPTF6flLVH
name                :	nu_numu2nutau_nue2numu_dunevd10kt_1x8x6_3view_30deg_946_153_20230802T232007Z_gen_g4_detsim_hitreco__20240224T091815Z_reco2_Pandora_Events.pndr
namespace           :	fardet-vd
retired             :	True
retired_by          :	dunepro
retired_timestamp   :	1710851823.235237
size                :	39266760
updated_by          :	schellma
updated_timestamp   :	1709511692.794404
parents:
   fardet-vd:nu_numu2nutau_nue2numu_dunevd10kt_1x8x6_3view_30deg_946_153_20230802T232007Z_gen_g4_detsim_hitreco.root (79818574)
<html><body><h2>Application error</h2>
            <h3>list index out of range</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata/products/webpie/current/webpie/WPApp.py", line 651, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata/products/webpie/current/webpie/WPApp.py", line 444, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata/products/webpie/current/webpie/WPApp.py", line 442, in _handle_request
    return subhandler(request, relpath, **args)
  File "/home/dbidata/products/metacat_server/dune/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "/home/dbidata/products/metacat_server/dune/server/data_handler.py", line 1138, in update_file
    f.set_parents(parents)
  File "/home/dbidata/products/metacat_server/dune/lib/metacat/common/dbbase.py", line 18, in decorated
    return method(first, *params, transaction=transaction, **args)
  File "/home/dbidata/products/metacat_server/dune/lib/metacat/db/dbobjects2.py", line 894, in set_parents
    transaction.executemany(f"""
  File "/home/dbidata/products/wsdbtools/current/wsdbtools/transaction.py", line 37, in executemany
    self.Cursor.execute(*params, **args)
IndexError: list index out of range
</pre>
            </body>
            </html>
checksums:
    adler32   : 648e7fbd
created_timestamp   :	2024-02-24 10:07:36.816310+00:00
creator             :	dunepro
fid                 :	UHIgc9HPTF6flLVH
name                :	nu_numu2nutau_nue2numu_dunevd10kt_1x8x6_3view_30deg_946_153_20230802T232007Z_gen_g4_detsim_hitreco__20240224T091815Z_reco2_Pandora_Events.pndr
namespace           :	fardet-vd
retired             :	True
retired_by          :	dunepro
retired_timestamp   :	1710851823.235237
size                :	39266760
updated_by          :	schellma
updated_timestamp   :	1709511692.794404
parents:
   fardet-vd:nu_numu2nutau_nue2numu_dunevd10kt_1x8x6_3view_30deg_946_153_20230802T232007Z_gen_g4_detsim_hitreco.root (79818574)

**Comment by marcmengel** [comment]
I think this may have been fixed a while ago... we had a problem where executemany down in the low level libraries was defined wrong.  Are you still seeing this?

**Comment by StevenCTimm** [comment]
We haven't done a big enough batch of update parents in recent months so that we would know one way or another.
Can try to do a few, if you want.

**Comment by marcmengel** [comment]
So this particular error trace  I believe was due to an error in the lower-level wsdbtools package (which was calling `execute() `rather than `executemany()` leading to this stack trace)  which was patched, but got un-patched when we migrated to AL9;  so when you were running this we had some servers with the errors and others not...
This should be cleared up now; if you have a chance to retest, please do.

**Comment by marcmengel** [comment]
Okay, so no new reports of this in almost 3 months, closing this out.
