### ISSUE TITLE
problem with metacat file update --parents

### ISSUE THREAD

**Issue by StevenCTimm** [fermitools/metacat#33]
I am trying to do a metacat file update --parents from the CLI but can't form the right syntax

metacat file update fardet-hd:nu_dune10kt_1x2x6_1412_481_20230826T153327Z_gen_g4_detsim_hitreco__20240229T162543Z_reco2.root --parents '[ {"fid": "80254757"} ]' --replace

The above throws an exception

<html><body><h2>Application error</h2>
            <h3>Can not convert to a Response: (ValueError('File [ {"fid": "80254757"} ] not found'),)</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 656, in wsgi_call
    response = makeResponse(response)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 200, in makeResponse
    raise ValueError("Can not convert to a Response: " + repr(resp))
ValueError: Can not convert to a Response: (ValueError('File [ {"fid": "80254757"} ] not found'),)
</pre>
            </body>
            </html>

If I do an update with --parents '-' 
which removes the parents, that works.. it's just a question of getting the right format I think.

[dunepro@dunesl7gpvm01 utilities]$ metacat file show -i 80254757
checksums:
    adler32   : 26defea7
created_timestamp   :	2023-08-28 10:48:31.560534+00:00
creator             :	dunepro
fid                 :	80254757
name                :	nu_dune10kt_1x2x6_1412_481_20230826T153327Z_gen_g4_detsim_hitreco.root
namespace           :	fardet-hd
retired             :	False
retired_by          :	None
retired_timestamp   :	None
size                :	1354145043
updated_by          :	dunepro
updated_timestamp   :	1711936572.479352
[dunepro@dunesl7gpvm01 utilities]$ metacat file show fardet-hd:nu_dune10kt_1x2x6_1412_481_20230826T153327Z_gen_g4_detsim_hitreco__20240229T162543Z_reco2.root
checksums:
    adler32   : 1f28975e
created_timestamp   :	2024-02-29 17:18:47.147378+00:00
creator             :	dunepro
fid                 :	m2aJImIARnKPGNdJ
name                :	nu_dune10kt_1x2x6_1412_481_20230826T153327Z_gen_g4_detsim_hitreco__20240229T162543Z_reco2.root
namespace           :	fardet-hd
retired             :	False
retired_by          :	None
retired_timestamp   :	None
size                :	1708704861
updated_by          :	dunepro
updated_timestamp   :	1709227175.821539

**Comment by marcmengel** [comment]
@StevenCTimm , Is this still an issue?  I interpret the error you got, above, as using a non-existent FID value for the parent file, but I'm not sure.

**Comment by StevenCTimm** [comment]
I haven't tried in a while..there are several metacat update issues that have been sitting around.
The FID in question did and does exist, the metacat file show info is pasted in the issue above.
What worked was first to set the parents to "-" and then to add the parents on a second update call.
The child file in metacat if you look at it does have the desired parentage now.
But according to the docs it should have been possible to do it in one call, not two
using the --replace option.

**Comment by marcmengel** [comment]
So based on the test case above passnig, I'm closing this.
