### ISSUE TITLE
dataset queries do not like leading numbers in dataset names.  "files from protodune-sp:2gevtodelete_74942485 " fails

### ISSUE THREAD

**Issue by hschellman** [fermitools/metacat#45]
metacat query “files from protodune-sp:2gevtodelete_74942485 limit 1”
MQLSyntaxError: No terminal matches ‘2’ in the current parser context, at line 1 col 26
files from protodune-sp:2gevtodelete_74942485 limit 1
             ^
Expected one of:
	* FNAME

**Comment by yuyiguo** [comment]
In addition, The wildcard searching gave errors too.

`files from datasets matching protodune-sp:"%gevtodelete_74942485"`
or
`files from datasets matching protodune-sp:"gevtodelete_74942485%"`

Application error
MQL syntax Error: No terminal matches '"' in the current parser context, at line 1 col 43 les from datasets matching protodune-sp:"%gevtodelete_74942485" ^ Expected one of: * PATTERN
Traceback (most recent call last):
  File "/home/dbidata/products/metacat_server/dune/lib/metacat/mql/mql10.py", line 1365, in parse
    parsed = _Parser.parse(text)
  File "/home/dbidata/products/metacat_server/venv/lib64/python3.9/site-packages/lark/lark.py", line 658, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/home/dbidata/products/metacat_server/venv/lib64/python3.9/site-packages/lark/parser_frontends.py", line 104, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/home/dbidata/products/metacat_server/venv/lib64/python3.9/site-packages/lark/parsers/earley.py", line 279, in parse
    to_scan = self._parse(lexer, columns, to_scan, start_symbol)
  File "/home/dbidata/products/metacat_server/venv/lib64/python3.9/site-packages/lark/parsers/xearley.py", line 152, in _parse
    to_scan = scan(i, to_scan)
  File "/home/dbidata/products/metacat_server/venv/lib64/python3.9/site-packages/lark/parsers/xearley.py", line 125, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan},
lark.exceptions.UnexpectedCharacters: No terminal matches '"' in the current parser context, at line 1 col 43

les from datasets matching protodune-sp:"%gevtodelete_74942485"
                                        ^
Expected one of: 
	* PATTERN

**Comment by marcmengel** [comment]
That second item is actually upset about the quotes.  If you just do 
`files from datasets matching protodune-sp:%gevtodelete_74942485`
that should work.
I will look into the parser issue with leading digits; but I'm actually surprised it accepts dataset  names with leading digits at all -- It probably shouldn't have let you declare a dataset name like that to begin with...

**Comment by marcmengel** [comment]
So it looks like we could just tweak the "lark" grammar in metacat/mql/grammar/common.py, and change
`FNAME: LETTER ("_"|"-"|"."|LETTER|DIGIT|"/")*`
to
`FNAME: ("_"|"-"|"."|LETTER|DIGIT|"/")+`
and not require filenames/namespace names to start with a letter.  This could lead to confusion with numbers in the
grammar, but I after some poking around don't think there is anyplace in the grammar where we have to distinguish between a filename and a number, so I *think* it may be happy, it's worth a try.

**Comment by marcmengel** [comment]
Closing this as resolved in #48
