### ISSUE TITLE
if presented a adler32 checksum value, metacat should verify that it is 8 hex digits

### ISSUE THREAD

**Issue by StevenCTimm** [fermitools/metacat#46]
We were recently able to (inadvertently) declare a file to metacat with a malformed checksum field.

metacat file show  neardet-2x2-minerva:TS1_00001673_0006_pdstl_v09_2405101604_RawData.dat
checksums:
    adler32   : 17a76ec
created_timestamp   :	2024-07-12 18:12:15.174545+00:00
creator             :	dunepro
fid                 :	83474439
name                :	TS1_00001673_0006_pdstl_v09_2405101604_RawData.dat
namespace           :	neardet-2x2-minerva
retired             :	False
retired_by          :	None
retired_timestamp   :	None
size                :	142702238
updated_by          :	None
updated_timestamp   :	1720807935.174545

If an adler32 value is presented, server should check to be sure that it is 8 digits as it should be.

**Comment by StevenCTimm** [comment]
(padding with zeros is allowed)

**Comment by marcmengel** [comment]
Closing this as being resolved in #47.
