### ISSUE TITLE
metacat retire file doesn't retire the file.

### ISSUE THREAD

**Issue by StevenCTimm** [fermitools/metacat#5]
[dunepro@dunesl7gpvm01 mcruciosam]$ metacat file show protodune-sp:PDSPProd4a_protoDUNE_sp_reco_stage1_p2GeV_35ms_sce_off_66954965_181_20240125T135618Z.root
checksums:
    adler32   : d3d1ae01
created_timestamp   :	2024-01-26 02:10:35.163075+00:00
creator             :	dunepro
fid                 :	81901138
name                :	PDSPProd4a_protoDUNE_sp_reco_stage1_p2GeV_35ms_sce_off_66954965_181_20240125T135618Z.root
namespace           :	protodune-sp
retired             :	False
retired_by          :	None
retired_timestamp   :	None
size                :	2014117646
updated_by          :	None
updated_timestamp   :	1706235035.163075
[dunepro@dunesl7gpvm01 mcruciosam]$ metacat file retire protodune-sp:PDSPProd4a_protoDUNE_sp_reco_stage1_p2GeV_35ms_sce_off_66954965_181_20240125T135618Z.root
[dunepro@dunesl7gpvm01 mcruciosam]$ echo $?
0
[dunepro@dunesl7gpvm01 mcruciosam]$ metacat file show protodune-sp:PDSPProd4a_protoDUNE_sp_reco_stage1_p2GeV_35ms_sce_off_66954965_181_20240125T135618Z.root
checksums:
    adler32   : d3d1ae01
created_timestamp   :	2024-01-26 02:10:35.163075+00:00
creator             :	dunepro
fid                 :	81901138
name                :	PDSPProd4a_protoDUNE_sp_reco_stage1_p2GeV_35ms_sce_off_66954965_181_20240125T135618Z.root
namespace           :	protodune-sp
retired             :	False
retired_by          :	None
retired_timestamp   :	None
size                :	2014117646
updated_by          :	None
updated_timestamp   :	1706235035.163075

**Comment by StevenCTimm** [comment]
Note that this applies only to the metacat CLI.  Line 321 of metacat_file.py has one extra "not" that shouldn't be there.


The python webapi works fine
>>> from metacat.webapi import MetaCatClient
>>> metacat_client=MetaCatClient("https://metacat.fnal.gov:9443/dune_meta_prod/app")
>>> metacat_client.retire_file(did="protodune-sp:PDSPProd4a_protoDUNE_sp_reco_stage1_p2GeV_35ms_sce_datadriven_66954965_97_20240125T080334Z.root", retire=True)
{'fid': '81893585', 'namespace': 'protodune-sp', 'name': 'PDSPProd4a_protoDUNE_sp_reco_stage1_p2GeV_35ms_sce_datadriven_66954965_97_20240125T080334Z.root', 'retired': True, 'retired_by': 'dunepro', 'updated_by': None, 'retired_timestamp': 1709176967.370436, 'updated_timestamp': 1706194812.866581, 'created_timestamp': 1706194812.866581, 'checksums': {'adler32': '3f5641af'}, 'size': 2012284302, 'creator': 'dunepro'}

**Comment by StevenCTimm** [comment]
Where do we get the updated client--download from trunk?

**Comment by marcmengel** [comment]
For the moment; I'm going to try to try to get it added under a new name to Pypi soon.
(maybe metacat_client?) as per Pypi policy we can't take over the old project name there for a year...

**Comment by marcmengel** [comment]
Folks can fetch it via:
https://pypi.org/project/metacat-client/3.43.0/
so that's 'metacat-client' vs 'metacat' for those installing it via pip
